name: Run all tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install arm-gcc
      run: |
        sudo apt-get install gcc-arm-none-eabi libnewlib-arm-none-eabi

    - name: Install avr-gcc
      run: |
        sudo apt-get install -y binutils-avr gcc-avr avr-libc

    - name: Install avra
      run: |
        git clone https://github.com/mnaberez/avra.git
        make -C avra/src -f makefiles/Makefile.linux
        echo "$PWD/avra/src" >> $GITHUB_PATH

    - name: Install asxxxx
      run: |
        wget -q -U github http://6502.org/tools/asm/asxv5p31.zip
        unzip -q asxv5p31.zip
        make -C asxv5pxx/asxmak/linux/build all
        echo "$PWD/asxv5pxx/asxmak/linux/build" >> $GITHUB_PATH

    - name: Install srecord
      run: sudo apt-get install srecord

    - name: Run all tests
      run: |
        python faceplate_emulator/host/setup.py test -q
        make -C faceplate_emulator/firmware
        make -C kwp1281_tool/firmware
        make -C reverse_engineering/clarion/vw_premium_4/disasm/pu1666a_mainmcu
        make -C reverse_engineering/clarion/vw_premium_4/disasm/pu1666a_submcu
        make -C reverse_engineering/delco/seat_liceo/disasm
        make -C reverse_engineering/delco/vw_premium_5/disasm
        make -C reverse_engineering/delco/vw_premium_5/custom/dumpram
        make -C reverse_engineering/delco/vw_premium_5/custom/faultcodes
        make -C reverse_engineering/delco/vw_premium_5/custom/loopback_irq
        make -C reverse_engineering/delco/vw_premium_5/custom/loopback_poll
        make -C reverse_engineering/delco/vw_premium_5/custom/serial_tx
        make -C reverse_engineering/technisat/vw_gamma_5/disasm
        make -C reverse_engineering/technisat/vw_rhapsody/disasm
        make -C tape_emulator/firmware
        make -C volume_monitor/firmware
